### PR TITLE
Update GradleUtil.java

### PR DESCRIPTION
**Pull request by Horstexplorer**
changed shadowJar version from 4.0.4 to 6.0.0 - this might help circumvents errors occuring with java 13

### CODE REVIEW

**Review by markozajc — APPROVED** [review]
good work i approve yes

**Comment by kantenkugel** [comment]
Was this checked to

- still work with older java versions (java 8)
- still work with older gradle versions (!gradleproject still building with gradle version 4.10.2 for example) https://github.com/Almighty-Alpaca/JDA-Butler/blob/85ca03b336ec65cdd7d7a8953b2e66b0c65ecc4e/bot/src/main/java/com/almightyalpaca/discord/jdabutler/util/gradle/GradleDownloader.java#L18
- and if gradle version is bumped due to point 2: does this still work with java 8 and old projects (no change required)

**Comment by Horstexplorer** [comment]
Java | Gradle | shadow | Result
-- | -- | -- | --
8 | 4.10.2 | 4.0.4 | works just fine
8 | 6.1 | 4.0.4 | works just fine
8 | 6.5 | 6.0.0 | works just fine
13 | 4.10.2 | 4.0.4 | works just fine
13 | 6.1 | 4.0.4 | unsupported class file major version 57
13 | 4.10.2 | 6.0.0 | supports Gradle 6.0+ only

It seems necessary to bump the gradle version aswell.
I am not able to tell if this will work fine with older projects as there might be other dependencies involved. Just for my quick -empty project + change version- test it seems fine. (same for the gradleproject)

**Comment by kantenkugel** [comment]
Testing this and a few other changes in some testing branch before merging into master

**Pull request merged**
